// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-G26Kr1NEpYxItFdXIPU9W0QJeOdL6Vo',
    appId: '1:97566881565:web:befbdd9e31abecf99fd3f4',
    messagingSenderId: '97566881565',
    projectId: 'todo-multilingual',
    authDomain: 'todo-multilingual.firebaseapp.com',
    storageBucket: 'todo-multilingual.appspot.com',
    measurementId: 'G-HN3S8XCK0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGUrFL6Zf6_9hGJ2_fza61SCfhrvv0Ruw',
    appId: '1:97566881565:android:c41234d67f73203c9fd3f4',
    messagingSenderId: '97566881565',
    projectId: 'todo-multilingual',
    storageBucket: 'todo-multilingual.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl7MZsBbZ-lyqpuxdd-b8SrIGQGo1_Pes',
    appId: '1:97566881565:ios:4bfd42dfa2097bb39fd3f4',
    messagingSenderId: '97566881565',
    projectId: 'todo-multilingual',
    storageBucket: 'todo-multilingual.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl7MZsBbZ-lyqpuxdd-b8SrIGQGo1_Pes',
    appId: '1:97566881565:ios:4bfd42dfa2097bb39fd3f4',
    messagingSenderId: '97566881565',
    projectId: 'todo-multilingual',
    storageBucket: 'todo-multilingual.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-G26Kr1NEpYxItFdXIPU9W0QJeOdL6Vo',
    appId: '1:97566881565:web:739a3326bfefd17e9fd3f4',
    messagingSenderId: '97566881565',
    projectId: 'todo-multilingual',
    authDomain: 'todo-multilingual.firebaseapp.com',
    storageBucket: 'todo-multilingual.appspot.com',
    measurementId: 'G-FHQL92P3CL',
  );
}
